#!/bin/bash

if [ ! -f /opt/adsb/scripts/common.sh ]
then
    echo "missing /opt/adsb/scripts/common.sh -- that's generally a bad sign"
else
    . /opt/adsb/scripts/common.sh
    rootcheck
    logparent
fi

# we rotate hourly to reduce the risk of overflowing /run - but we only rotate log if longer than 3000 lines
# at that point we copy the log to the on disk log directory
if [[ -f /run/adsb-feeder-image.log ]] && (( $(wc -l < /run/adsb-feeder-image.log) > 3000 )); then
    TIMESTAMP=$(date +%Y-%m-%d+%H:%M)
    mkdir -p /opt/adsb/logs
    cp /run/adsb-feeder-image.log /opt/adsb/logs/adsb-setup.log."$TIMESTAMP"
    truncate -s 0 /run/adsb-feeder-image.log
    find . -name /opt/adsb/logs/adsb-setup.log.\* -ctime +7 | xargs rm -f
fi

# if this is the update check at 1:30am, do the updates if configured
currenttime=$(TZ=$(grep TZ /opt/adsb/config/.env | cut -d= -f2) date '+%H:%M')
if [[ "$currenttime" > "01:20" ]] || [[ "$currenttime" < "01:40" ]]; then
    # check in the .env file what we should do
    if grep -q "^AF_IS_NIGHTLY_BASE_UPDATE_ENABLED=True" config/.env ; then
        # do an OS update - either using the DietPi update tool or by just using apt
        if [ -x /boot/dietpi/dietpi-update ] ; then
            G_INTERACTIVE=0 CONFIG_CHECK_APT_UPDATES=2 dietpi-update 1 >> /run/adsb-feeder-image.log 2>&1
        else
            apt update >> /run/adsb-feeder-image.log 2>&1
            apt upgrade -y >> /run/adsb-feeder-image.log 2>&1
        fi
    fi
    if grep "^AF_IS_NIGHTLY_FEEDER_UPDATE_ENABLED=True" config/.env ; then
        bash /opt/adsb/feeder-update
    fi
fi
