#!/usr/bin/env bash
# adsb-pi-setup python web app
# <Description what this module does>
# Written by Dirk Hohndel <dirk@hohndel.org>
# AGPL V3
########


# Source error handling, leave this in place
set -x
set -e

source /common.sh
install_cleanup_trap

# all we do is save the correct kernel for later use
# first copy is to make sure we don't end up with a symlink
cp /boot/vmlinuz* /tmp/vmlinuz
custompios_export kernel /tmp/vmlinuz
