services:
  1090uk:
    image: ${TNUK_CONTAINER}
    healthcheck:
      disable: true
    tty: true
    container_name: radar1090uk
    restart: unless-stopped
    cpu_period: 50000
    cpu_quota: 7500
    environment:
      - TZ=${FEEDER_TZ}
      - RADAR1090_KEY=${FEEDER_1090UK_API_KEY}
      - VERBOSE=false
      - BEASTHOST=ultrafeeder
      - S6_KILL_GRACETIME=1000
      # USER_PROVIDED_ENV_START
      # USER_PROVIDED_ENV_END
    tmpfs:
      - /run:exec,size=256M
      - /tmp:size=128M
      - /var/log:size=32M
