services:
  acarsdec2:
    image: ${ACARSDEC_CONTAINER}
    container_name: acarsdec2
    restart: always
    environment:
      # - QUIET_LOGS=true
      - TZ=${FEEDER_TZ}
      - SOAPYSDR=${ACARS2_SDR_STRING}
      - GAIN=${ACARS2_GAIN}
      # the default frequencies are 'lower frequencies up to 130.85MHz' in acarsdec, higher ones in acarsdec2
      - FREQUENCIES=${ACARS2_FREQUENCIES:-131.85;131.825;131.725;131.65;131.55;131.525;131.475;131.45;131.425;131.25;131.125}
      - FEED_ID=${ACARS2_FEED_ID}
      - OUTPUT_SERVER=acars_router
    tmpfs:
      - /run:exec,size=64M
      - /var/log:size=64M
    device_cgroup_rules:
      - "c 189:* rwm"
    volumes:
      - /dev/bus/usb:/dev/bus/usb:ro
