services:
  adsbhub_STAGE2NUM:
    image: ${AH_CONTAINER}
    healthcheck:
      disable: true
    container_name: adsbhub_STAGE2NUM
    hostname: adsbhub_STAGE2NUM
    restart: unless-stopped
    networks:
      - adsb_im_bridge
    cpu_period: 50000
    cpu_quota: 7500
    stop_grace_period: 3s
    environment:
      - TZ=${FEEDER_TZ_STAGE2NUM}
      - SBSHOST=uf_STAGE2NUM
      - CLIENTKEY=${FEEDER_ADSBHUB_STATION_KEY_STAGE2NUM}
      - S6_KILL_GRACETIME=1000
      # USER_PROVIDED_ENV_START
      # USER_PROVIDED_ENV_END
    volumes:
      - /dev/null:/root/.wget-hsts
    tmpfs:
      - /run:exec,size=64M
      - /var/log
