#!/bin/bash

# this needs to run as root
if [ $(id -u) != "0" ] ; then
	echo "this command requires superuser privileges - please run as sudo bash $0"
	exit 1
fi

cd /opt/adsb
TIME=$(date -Iseconds)

# this shell script no longer changes or downloads docker.image.versions, this only happens during feeder-update
# it now merely pulls the container versions as set in config.json / .env

echo "$(date -Iseconds): pulling new container images and restarting docker" >> /opt/adsb/adsb-setup.log
bash ./docker-pull.sh
bash /opt/adsb/docker-compose-start

# finally remove the images and files we no longer use - but only if this is the image we are running
# this would be rude to do on a system where we are one of many apps potentially using docker.
[ -f os.adsb.feeder.image ] && docker system prune -f

sed -i "s/CONTAINER_VERSION=.*/CONTAINER_VERSION=$TIME/" /opt/adsb/config/.env

echo "$(date -Iseconds): done" >> /opt/adsb/adsb-setup.log
