services:
  dumpvdl2:
    image: ${DUMPVDL2_CONTAINER}
    container_name: dumpvdl2
    restart: always
    environment:
      #    - QUIET_LOGS=true
      - TZ=${FEEDER_TZ}
      - SOAPYSDR=${VDL2_SDR_STRING}
      - GAIN=${VDL2_GAIN}
      - FREQUENCIES=${VDL2_FREQUENCIES:-136975000 136945000 136925000 136825000 136800000 136775000}
      - FEED_ID=${VDL2_FEED_ID}
      - VDL2_FILTER_ENABLE=true
      - ZMQ_MODE=server
      - ZMQ_ENDPOINT=tcp://0.0.0.0:45555
      - SERVER=
    tmpfs:
      - /run:exec,size=64M
      - /var/log:size=64M
    device_cgroup_rules:
      - "c 189:* rwm"
    volumes:
      - /dev/bus/usb:/dev/bus/usb:ro
