services:
  piaware_STAGE2NUM:
    image: ${FA_CONTAINER}
    healthcheck:
      disable: true
    tty: true
    container_name: piaware_STAGE2NUM
    restart: unless-stopped
    cpu_period: 50000
    cpu_quota: 7500
    stop_grace_period: 3s
    ports:
      - ${AF_PIAWAREMAP_PORT_STAGE2NUM:-8081}:8080
      - ${AF_PIAWARESTAT_PORT_STAGE2NUM:-8082}:80
    environment:
      - BEASTHOST=uf_STAGE2NUM
      - UAT_RECEIVER_TYPE=${FEEDER_PIAWARE_UAT978_STAGE2NUM}
      - UAT_RECEIVER_HOST=${FEEDER_UAT978_HOST_STAGE2NUM}
      - MLAT_RESULTS_BEASTHOST=uf_STAGE2NUM
      - MLAT_RESULTS_BEASTPORT=31004
      - LAT=${FEEDER_LAT_STAGE2NUM}
      - LONG=${FEEDER_LONG_STAGE2NUM}
      - TZ=${FEEDER_TZ_STAGE2NUM}
      - FEEDER_ID=${FEEDER_PIAWARE_FEEDER_ID_STAGE2NUM}
      - S6_KILL_GRACETIME=1000
      # USER_PROVIDED_ENV_START
      # USER_PROVIDED_ENV_END
    volumes:
      - /dev/null:/var/log/piaware/current
    tmpfs:
      - /run:exec,size=64M
      - /tmp:size=16M
      - /var/log:size=16M
