#!/bin/bash

# little silly helper functions
exit_with_message() { echo "$1" ; exit 1 ; }
cleanup() {
    # assuming things aren't too screwed up, let's try to start docker
    # and the setup app
    # that way the user might at least be able to look at the logs and figure out
    # what went wrong (or at least ask for help with more information)
    # make sure this doesn't fail if the kill fails for some reason
    if [ -f /opt/adsb-feeder-update/waiting-pid ] ; then kill "$(</opt/adsb-feeder-update/waiting-pid)" || true ; fi
    rm -f /opt/adsb-feeder-update/waiting-pid
    /opt/adsb/docker-compose-start
    systemctl start adsb-setup.service;
}

waiting_placeholder() {
    PORT=$(grep _ADSBIM_STATE_WEBPORT /opt/adsb/config/.env | cut -d= -f2)
    python3 /opt/adsb/adsb-setup/waiting-app.py "$PORT" &
    mkdir -p /opt/adsb-feeder-update
    echo $! > /opt/adsb-feeder-update/waiting-pid
}

# we need more help debugging this
set -x

exec &>> /var/log/adsb-setup.log

trap cleanup EXIT

LAST_ARG=${!#}
if [[ $LAST_ARG == "-go" ]]; then
    # that means we just refreshed the git tree and the first argument is the target
    TARGET="$1"
    BRANCH="$2"
else
    if [[ $LAST_ARG == "-wait" ]]; then
        # we were called from the feeder-update-service... and in order for the web UI to be
        # able to wait for the update to succeed, we need to give it a few seconds to show the
        # waiting page and set things up
        sleep 5
    fi
    # this makes sure that the user can't interact with the UI while we are potentially
    # making changes under the hood
    echo "stop the running service"
    systemctl stop adsb-setup.service
    waiting_placeholder

    # we want to get the correct (matching) update script. But to do
    # that we need to figure out which one that is.
    # (that last arg pattern has downsides... we can't just skip them, so filter out non-branch arguments here)
    if [[ "$1" == "" || "$1" == -* ]] ; then
        # called without argument, so check which channel we are updating to
        if [ -f /opt/adsb/update-channel ] ; then
            TARGET=$(</opt/adsb/update-channel)
        else
            # ok, no channel either... can we guess from the current version?
            TARGET=$(sed 's/.*(\(.*\)).*/\1/' < /opt/adsb/adsb.im.version)
            if [ "$TARGET" = "$(cat /opt/adsb/adsb.im.version)" ] ; then
                # running out of ideas - let's just go with stable
                BRANCH="stable"
            fi
        fi
    else
        # the command line told us what to get. Nice.
        TARGET="$1"
    fi
    [ -z "$BRANCH" ] && BRANCH="$TARGET"
    mkdir -p /opt/adsb-feeder-update
    cd /opt/adsb-feeder-update || exit_with_message "can't cd /opt/adsb-feeder-update"
    [ -d adsb-feeder-image ] || git clone https://github.com/dirkhh/adsb-feeder-image || exit_with_message "git clone failed, giving up"
    cd adsb-feeder-image || exit_with_message "can't cd /opt/adsb-feeder-update/adsb-feeder-image"
    # we're in the checked out directory - make sure it's the latest
    # don't hide the output as that could be useful in the logs
    git fetch || exit_with_message "git fetch in /opt/adsb-feeder-update/adsb-feeder-image failed"
    # 'stable' and 'beta' are special, they refer to tags.
    # everything else is interpreted as a branch or a hash
    if [[ "$TARGET" == "beta" ]] ; then
        # for the beta channel, grab the last beta tag
        TARGET=$(git tag --sort=version:refname|grep beta|tail -1)
    elif [[ "$TARGET" == "stable" ]] ; then
        # for the stable channel, grab the last non-beta tag
        TARGET=$(git tag --sort=version:refname|grep -v beta|tail -1)
    fi
    # move to a temporary branch in order to be able to delete the branch we want to update to
    # this avoids "non-ff" issues after force pushes
    FAKE_BRANCH="${RANDOM}-${RANDOM}"
    git checkout -b "$FAKE_BRANCH" &> /dev/null
    git branch -D "$TARGET" &> /dev/null || true
    git checkout "$TARGET" &> /dev/null
    git branch -D "$FAKE_BRANCH" &> /dev/null
    echo "restarting with feeder-update from $TARGET"
    cp src/modules/adsb-feeder/filesystem/root/opt/adsb/feeder-update /opt/adsb-feeder-update/feeder-update
    # add a trailing '-go' argument, and the correct target as first argument; this way the call should
    # be compatible with older versions of the script - not that anyone should want to downgrade using this script
    XTRACE="" && [[ -o xtrace ]] && XTRACE="-x"
    if [ -f /opt/adsb-feeder-update/feeder-update ] ; then
        # the cleanup trap will be re-initialized in the child script, so disable it here
        trap - EXIT
        bash "$XTRACE" /opt/adsb-feeder-update/feeder-update "$TARGET" "$BRANCH" "$@" -go
    else
        echo "can't find /opt/adsb-feeder-update/feeder-update after update to $TARGET"
    fi
    exit "$?"
fi

# now we know that we are running the right script in the right place
DIR=$(dirname -- "$(readlink -f "${BASH_SOURCE[0]}")")
echo "running ${DIR}/feeder-update from $TARGET"

cd "${DIR}/adsb-feeder-image" || exit_with_message "can't cd to ${DIR}/adsb-feeder-image"

DATE_COMPONENT=$(git log -20 --date=format:%y%m%d --format="%ad" | uniq -c | head -1 | awk '{ print $2"."$1 }')
# grab the most recent tag. Forcing '--long' always adds the -<num>-g<sha> trailer to the result - which we then can remove
TAG_COMPONENT=$(git describe --match "v[0-9]*" --long | sed "s/-[0-9]*-g[0-9a-f]*//")
VERSION="${TAG_COMPONENT}(${BRANCH})-${DATE_COMPONENT}"
echo "starting the actual upgrade to ${VERSION}"

echo "prepare the files that we need to replace"
mkdir -p "${DIR}/root"
cp -r src/modules/adsb-feeder/filesystem/root "${DIR}"

echo "copy the updated files in place"
# shellcheck disable=SC2164
cd "${DIR}/root"

# if this an app and not the full image, prune some of the files that aren't
# wanted for the app and copy the trees we need over
if [ ! -f /opt/adsb/os.adsb.feeder.im ] ; then
    rm -f ./usr/lib/systemd/system/adsb-bootstrap.service
    cp -a ./usr/lib/systemd/system/* /etc/systemd/system/
    cp -a ./opt/adsb/* /opt/adsb
else
    # copy the complete tree into the / filesystem
    cp -r . /
fi
# since the next run won't be a clean first start, we need to manually
# mv the potentially updated .yml files into place and keep backups of
# any that might have been changed
# shellcheck disable=SC2164
cd /opt/adsb
for ymlfile in *.yml; do
    cmp "$ymlfile" "config/$ymlfile" &> /dev/null || mv -f "config/$ymlfile" "config/${ymlfile}.bak"
    mv -f "$ymlfile" "config/$ymlfile"
done

# make sure the version information is correct
echo "$VERSION" > /opt/adsb/adsb.im.version
sed -i "s/BASE_VERSION=.*/BASE_VERSION=$VERSION/" /opt/adsb/config/.env

echo "finally, trigger a container upgrade so that they match the new image"
/opt/adsb/docker-update-adsb-im -no-fetch

echo "restart the service"
trap - EXIT
systemctl daemon-reload
if [ -f /opt/adsb-feeder-update/waiting-pid ] ; then kill "$(</opt/adsb-feeder-update/waiting-pid)" || true ; fi
rm -f /opt/adsb-feeder-update/waiting-pid

systemctl start adsb-setup.service

echo "update to ${VERSION} complete"
