services:
  opensky:
    image: ${OS_CONTAINER}
    healthcheck:
      disable: true
    tty: true
    container_name: opensky
    restart: always
    cpu_period: 50000
    cpu_quota: 7500
    environment:
      - TZ=${FEEDER_TZ}
      - BEASTHOST=ultrafeeder
      - LAT=${FEEDER_LAT}
      - LONG=${FEEDER_LONG}
      - ALT=${FEEDER_ALT_M}
      - OPENSKY_USERNAME=${FEEDER_OPENSKY_USERNAME}
      - OPENSKY_SERIAL=${FEEDER_OPENSKY_SERIAL}
      - S6_KILL_GRACETIME=1000
      # USER_PROVIDED_ENV_START
      # USER_PROVIDED_ENV_END
    tmpfs:
      - /run:exec,size=64M
      - /var/log
