services:
  pfclient:
    image: ${PF_CONTAINER}
    healthcheck:
      disable: true
    device_cgroup_rules:
      # serial devices
      - 'c 188:* rwm'
    container_name: pfclient
    hostname: pfclient
    restart: unless-stopped
    networks:
      - adsb_im_bridge
    cpu_period: 50000
    cpu_quota: 7500
    stop_grace_period: 3s
    ports:
      - ${AF_PLANEFINDER_PORT:-30053}:30053
    environment:
      - TZ=${FEEDER_TZ}
      # if RADAR_STICK is true, BEASTHOST is ignored by the container
      # the data flow is reversed, ultrafeeder will pull data from this container
      - RADAR_STICK=${PF_RADAR_STICK_ENABLED}
      - BEASTHOST=ultrafeeder
      - LAT=${FEEDER_LAT}
      - LONG=${FEEDER_LONG}
      - SHARECODE=${FEEDER_PLANEFINDER_SHARECODE}
      - S6_KILL_GRACETIME=1000
      # USER_PROVIDED_ENV_START
      # USER_PROVIDED_ENV_END
    volumes:
      - /dev:/dev:ro
    tmpfs:
      - /run:exec,size=64M
      - /var/log/pfclient
