services:
  sdrplay-beast1090:
    image: ghcr.io/sdr-enthusiasts/docker-sdrplay-beast1090:latest-build-3
    tty: true
    container_name: sdrplay-beast1090
    hostname: sdrplay-beast1090
    restart: always
    device_cgroup_rules:
      - 'c 189:* rwm'
    volumes:
      - /dev/bus/usb:/dev/bus/usb:ro
      - /dev/shm:/dev/shm:rw
    tmpfs:
      - /run:exec,size=256M
      - /tmp:size=128M
      - /var/log:size=32M
    environment:
      - I_AGREE_TO_THE_SDRPLAY_LICENSE=${AF_IS_SDRPLAY_LICENSE_ACCEPTED}
      - DUMP1090_EXTRA_ARGS=--fix --max-range 500 --phase-enhance --lat ${FEEDER_LAT} --lon ${FEEDER_LONG} --adsbMode 1
