#!/bin/bash
#
# first replace the 'dangerous' parts of the expert setup
mkdir -p /opt/adsb/adsb-setup/backup
mv /opt/adsb/adsb-setup/templates/expert.html /opt/adsb/adsb-setup/backup/expert.html
awk '/SECURE_IMAGE_START/,/SECURE_IMAGE_END/{ next }; { print $0 }' < /opt/adsb/adsb-setup/backup/expert.html > /opt/adsb/adsb-setup/templates/expert.html
echo "restricted expert page"

# I don't see a reason to disable the running getty's
# systemctl disable --now getty@tty1
# systemctl disable --now serial-getty@ttyAMA0

# on Armbian images, we need to kill the running shells
# TODO
echo "not yet disabling Arbian shells"
