services:
  ultrafeeder_stage2_STAGE2NUM:
    image: ${ULTRAFEEDER_CONTAINER}
    tty: true
    container_name: ultrafeeder_stage2_STAGE2NUM
    hostname: ultrafeeder_STAGE2NUM
    restart: always
    ports:
      - ${AF_TAR1090_PORT_STAGE2NUM:-809STAGE2NUM}:80 # to expose the web interface
      - 311STAGE2NUM3:31003 # MLATHUB SBS output
      - 311STAGE2NUM4:31004 # MLATHUB Beast input
      - 311STAGE2NUM5:31005 # MLATHUB Beast output
      - 311STAGE2NUM6:31006 # MLATHUB Beast reduce output
    environment:
      # --------------------------------------------------
      # general parameters:
      - LOGLEVEL=error
      - TZ=${FEEDER_TZ_STAGE2NUM}
      #
      # --------------------------------------------------
      # readsb/decoder parameters:
      - BEASTHOST=${AF_MICRO_IP_STAGE2NUM}
      - READSB_LAT=${FEEDER_LAT_STAGE2NUM}
      - READSB_LON=${FEEDER_LONG_STAGE2NUM}
      - READSB_ALT=${FEEDER_ALT_M_STAGE2NUM}
      - READSB_MODEAC=false
      - READSB_RX_LOCATION_ACCURACY=2
      - READSB_STATS_RANGE=true
      # --write-state-only-on-exit only affects the heatmap/replay data and traces
      # this configuration has no traces and the heatmap/replay data are written every 30 min anyhow
      # docker stop ultrafeeder will result in proper readsb exit which writes the state anyhow
      - READSB_WRITE_STATE_ONLY_ON_EXIT=true
      # if the micro feeder includes a UAT SDR, use the replay feature so we connect to it only once
      - READSB_EXTRA_ARGS=${FEEDER_UAT_REPLAY978_STAGE2NUM}
      # Sources and Aggregator connections:
      # (Note - remove the ones you are not using / feeding)
      - ULTRAFEEDER_CONFIG=${FEEDER_ULTRAFEEDER_CONFIG_STAGE2NUM}
      - MLAT_USER=${MLAT_SITE_NAME_STAGE2NUM}
      - UUID=${ULTRAFEEDER_UUID_STAGE2NUM}
      #
      # --------------------------------------------------
      # TAR1090 (Map Web Page) parameters:
      - UPDATE_TAR1090=${UPDATE_TAR1090:-false}
      - TAR1090_MESSAGERATEINTITLE=true
      - TAR1090_PAGETITLE=${MLAT_SITE_NAME_STAGE2NUM}
      - TAR1090_SITENAME=${MLAT_SITE_NAME_STAGE2NUM}
      - TAR1090_PLANECOUNTINTITLE=true
      - TAR1090_FLIGHTAWARELINKS=true
      - HEYWHATSTHAT_PANORAMA_ID=${FEEDER_HEYWHATSTHAT_ID_STAGE2NUM}
      - HEYWHATSTHAT_ALTS=${FEEDER_HEYWHATSTHAT_ALTS:-1000ft,5000ft,10000ft,20000ft,30000ft,40000ft}
      - TAR1090_SITESHOW=true
      - TAR1090_RANGE_OUTLINE_COLORED_BY_ALTITUDE=true
      - TAR1090_RANGE_OUTLINE_WIDTH=1.5
      - TAR1090_RANGE_OUTLINE_DASH=${TAR1090_RANGE_OUTLINE_DASH}
      - TAR1090_RANGERINGSDISTANCES=${TAR1090_RANGERINGSDISTANCES:-50,100,150,200}
      - TAR1090_RANGERINGSCOLORS='#1A237E','#0D47A1','#42A5F5','#64B5F6'
      - TAR1090_USEROUTEAPI=${FEEDER_TAR1090_USEROUTEAPI}
      - TAR1090_ROUTEAPIURL="https://adsb.im/api/0/routeset"
      - TAR1090_IMAGE_CONFIG_LINK="http://HOSTNAME:${AF_WEBPORT}/"
      - TAR1090_IMAGE_CONFIG_TEXT="ADS-B Feeder Image Configuration"
      - TAR1090_ENABLE_AC_DB=true
      # --------------------------------------------------
      # GRAPHS1090 (Decoder and System Status Web Page) parameters:
      # The two 978 related parameters should only be included if you are running dump978 for UAT reception (USA only)
      - GRAPHS1090_REDUCE_IO=true
      # How often the statistics data the graphs are generated from are written to disk (in seconds)
      - GRAPHS1090_REDUCE_IO_FLUSH_IVAL=21600
      - GRAPHS1090_DARKMODE=true
      #- ENABLE_978=${FEEDER_ENABLE_UAT978_STAGE2NUM}
      #- URL_978=${FEEDER_URL_978_STAGE2NUM}
      #
      # USER_PROVIDED_ENV_START
      # USER_PROVIDED_ENV_END
    volumes:
      # CURRENT_IP=STAGE2IP
      - /opt/adsb/config/ultrafeeder/STAGE2IP/globe_history:/var/globe_history
      - /opt/adsb/config/ultrafeeder/STAGE2IP/graphs1090:/var/lib/collectd
      - /proc/diskstats:/proc/diskstats:ro
      - /dev:/dev:ro
      - /run/adsb-feeder-ultrafeeder_STAGE2NUM:/run
    tmpfs:
      - /tmp:size=128M
      - /var/log:size=32M
