services:
  dump978:
    image: ${UAT978_CONTAINER}
    healthcheck:
      disable: true
    container_name: dump978
    hostname: dump978
    restart: unless-stopped
    tty: false # work-around for /dev read-only mount + /dev/console error
    device_cgroup_rules:
      - 'c 189:* rwm'
      - 'c 188:* rwm'
    environment:
      - TZ=${FEEDER_TZ}
      - LAT=${FEEDER_LAT}
      - LON=${FEEDER_LONG}
      - DUMP978_RTLSDR_DEVICE=${FEEDER_SERIAL_978}
      - DUMP978_SDR_GAIN=${UAT_SDR_GAIN}
      - DUMP978_SDR_PPM=${UAT_SDR_PPM:-}
      - DUMP978_DEVICE_TYPE=${FEEDER_UAT_DEVICE_TYPE}
      - DUMP978_ENABLE_BIASTEE=${FEEDER_ENABLE_UATBIASTEE}
      - AUTOGAIN_INITIAL_PERIOD=7200
      - S6_KILL_GRACETIME=1000
      # USER_PROVIDED_ENV_START
      # USER_PROVIDED_ENV_END
    volumes:
      - /dev:/dev:ro
      - /opt/adsb/config/dump978/globe_history:/var/globe_history
    ports:
      - ${AF_UAT978_PORT:-9780}:80
      - 30978:30978
      - 30979:30979
    tmpfs:
      - /run:exec,size=64M
      - /run/stats:size=32M
      - /run/skyaware978:size=32M
      - /run/autogain:size=32M
      - /var/log

