services:
  webproxy:
    container_name: webproxy
    hostname: webproxy
    image: ${WEBPROXY_CONTAINER}
    healthcheck:
      disable: true
    restart: unless-stopped
    networks:
      - adsb_im_bridge
    ports:
      - ${AF_TAR1090_PORT:-8080}:80 # to expose the web interface
    environment:
      - S6_KILL_GRACETIME=1000
      - VERBOSE_LOG=ON
      # USER_PROVIDED_ENV_START
      # USER_PROVIDED_ENV_END
    tmpfs:
      - /run:exec,size=64M
      - /var/log
    volumes:
      - /opt/adsb/webproxy:/run/nginx
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

