#!/usr/bin/env bash
# adsb-pi-setup python web app
# <Description what this module does>
# Written by Dirk Hohndel <dirk@hohndel.org>
# AGPL V3
########


# Source error handling, leave this in place
set -x
set -e

source /common.sh
install_cleanup_trap

unpack /filesystem/root /

apt-get update --allow-releaseinfo-change

if  grep -q "bullseye" /etc/os-release ; then
	# for older Debian the packaged flask is still v1 and too old for our code
	# on the flipside, bullseye still allows us to use pip to install
	# systemwide packages - so let's do it this way
	apt-get install -y --no-install-recommends python3 python3-pip
	pip install --no-cache-dir -r /usr/local/share/adsb-pi-setup/requirements.txt
	ln -s /usr/local/bin/flask /usr/bin
else
	apt-get install -y --no-install-recommends python3 python3-flask
fi

