#!/usr/bin/env bash
# adsb-pi-setup python web app
# <Description what this module does>
# Written by Dirk Hohndel <dirk@hohndel.org>
# AGPL V3
########


# Source error handling, leave this in place
set -x
set -e

source /common.sh
install_cleanup_trap

unpack /filesystem/root /

apt-get update --allow-releaseinfo-change

if  grep -q "bullseye" /etc/os-release ; then
	# for older Debian the packaged flask is still v1 and too old for our code
	# on the flipside, bullseye still allows us to use pip to install
	# systemwide packages - so let's do it this way
	apt-get install -y --no-install-recommends python3 python3-pip
	pip install --no-cache-dir -r /usr/local/share/adsb-pi-setup/requirements.txt
	ln -s /usr/local/bin/flask /usr/bin
else
	apt-get install -y --no-install-recommends python3 python3-flask
fi

if grep -q "dietpi" /etc/dist_variant ; then
	# oh, lots of things things are different here...
	sed -i "s/AUTO_SETUP_LOCALE=.*/AUTO_SETUP_LOCALE=en_US.UTF-8/" /boot/dietpi.txt
	sed -i "s/AUTO_SETUP_KEYBOARD_LAYOUT=.*/AUTO_SETUP_KEYBOARD_LAYOUT=us/" /boot/dietpi.txt
	sed -i "s/AUTO_SETUP_NET_HOSTNAME=.*/AUTO_SETUP_NET_HOSTNAME=adsb-feeder/" /boot/dietpi.txt
	sed -i "s/AUTO_SETUP_HEADLESS=.*/AUTO_SETUP_HEADLESS=1/" /boot/dietpi.txt
	sed -i "s/AUTO_SETUP_AUTOMATED=.*/AUTO_SETUP_AUTOMATED=1/" /boot/dietpi.txt
	sed -i "s/AUTO_SETUP_GLOBAL_PASSWORD=.*/AUTO_SETUP_GLOBAL_PASSWORD=${ROOT_PWD}/" /boot/dietpi.txt
	sed -i "s/SURVEY_OPTED_IN=.*/SURVEY_OPTED_IN=0/" /boot/dietpi.txt
	sed -i "s/CONFIG_NTP_MODE=.*/CONFIG_NTP_MODE=4/" /boot/dietpi.txt
	sed -i "s/CONFIG_SERIAL_CONSOLE_ENABLE=.*/CONFIG_SERIAL_CONSOLE_ENABLE=0/" /boot/dietpi.txt
	# sed -i "s/AUTO_SETUP_NET_WIFI_ENABLED=.*/AUTO_SETUP_NET_WIFI_ENABLED=1/" /boot/dietpi.txt
	# sed -i "s/AUTO_SETUP_NET_WIFI_COUNTRY_CODE=.*B/AUTO_SETUP_NET_WIFI_COUNTRY_CODE=US/" /boot/dietpi.txt
fi
