#!/usr/bin/env bash
# finally create the version number file based on the date of the last commit
# Written by Dirk Hohndel <dirk@hohndel.org>
# GPL V3
########

set -x
set -e
git log -20 --date=format:%y%m%d --format="%ad" | uniq -c | head -1 | awk '{ print $2"."$1 }' >> /etc/adsb.im.version

