#!/usr/bin/env bash
# GPL V3
########
set -ex

# just to be sure - trying to do this late in the configuration
echo -e "$ROOT_PWD\n$ROOT_PWD" | (passwd root)
echo -e "$BASE_USER_PASSWORD\n$BASE_USER_PASSWORD" | (passwd pi)

sed -i "/127.0.1.1 $(hostname)/d" /etc/hosts
sed -i -e 's/.*Storage=.*/Storage=persistent/' /etc/systemd/journald.conf
sed -i -e 's/.*RuntimeMaxUse=.*/RuntimeMaxUse=10M/' /etc/systemd/journald.conf
sed -i -e 's/.*SystemMaxUse=.*/SystemMaxUse=128M/' /etc/systemd/journald.conf

# this isn't needed anymore and we want to make sure /var/cache is clean to save space
umount /var/cache/apt || true

# free up space
apt-get clean -y
find  /var/lib/apt/lists | grep -v InRelease | xargs rm -rf
rm -rf /tmp/* /var/log/* /var/cache/* /var/lib/dpkg/status-old

# remove pycache, nothing found doesn't mean failure thus always return true
find /usr | grep -E "/__pycache__$" | xargs rm -rf || true

# not sure where this binary comes from, remove it!
rm -f /usr/bin/qemu-aarch64-static

dd if=/dev/zero of=/zeroes bs=1M || true
rm -f /zeroes
