#!/usr/bin/env bash
# overall distro module for ADSB.lol image
# <Description what this module does>
# Written by Dirk Hohndel <dirk@hohndel.org>
# GPL V3
########


# Source error handling, leave this in place
set -x
set -e

source /common.sh
install_cleanup_trap

unpack /filesystem/home/pi /home/"${BASE_USER}" "${BASE_USER}"
unpack /filesystem/home/root /root root


# Unpack root at the end, so files are modified before
unpack /filesystem/root /

if [ "$BASE_DISTRO" = "armbian" ] ; then
	apt install -y network-manager net-tools

	echo "127.0.0.1 adsb-feeder.local" >> /etc/hosts

	# ensure that we get predictable interface names
	echo "extraargs=net.ifnames=0" >> /boot/armbianEnv.txt

	sed -i 's/Wants=network-online.target/Wants=network-pre.target/;s/After=network.target network-online.target/Before=wpa_supplicant.service network.target network-online.target/' /usr/lib/systemd/system/armbian-firstrun-config.service
	systemctl enable armbian-firstrun-config
fi
systemctl enable adsb-docker
export ROOT_PWD=$(openssl rand -base64 9)
echo -e "$ROOT_PWD\n$ROOT_PWD" | (passwd root)
export PI_PWD=$(openssl rand -base64 9)
echo -e "$PI_PWD\n$PI_PWD" | (passwd pi)
